version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: local
    tty: true
    stdin_open: true
    command: "air -c .air.toml"
    volumes:
      - .:/go/src/github.com/Sakamoto0525/zitadel
    ports:
      - 8080:8080
    networks:
      - zitadel-network

networks:
  zitadel-network:
    external:
      name: zitadel-network
